language: cpp

branches:
  except:
    - gh-pages

os:
  - linux

compiler:
  - clang
  - gcc

before_install:
  # GCC / Clang (Needed until Travis CI updates to Ubuntu 14.04+)
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  
  # Clang (Needed until Travis CI updates to Ubuntu 14.04+)
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  # CMake (Needed until Travis CI updates to Ubuntu 14.04+)
  - sudo add-apt-repository -y ppa:kalakris/cmake

  - sudo apt-get update -qq

install:
  # GCC
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq --force-yes g++-4.9; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  
  # Clang
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq --force-yes g++-4.8; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/clang-3.4 90; fi
  - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/clang++-3.4 90; fi
  
  # CMake (Needed until Travis CI updates to Ubuntu 14.04+)
  - sudo apt-get install -qq cmake
  
  # Armadillo C++
  - sudo apt-get install -qq libblas-dev
#  - sudo apt-get install -qq libopenblas-dev
  - sudo apt-get install -qq liblapack-dev
  - wget -O armadillo.tar.gz http://downloads.sourceforge.net/project/arma/armadillo-4.650.3.tar.gz
  - mkdir armadillo
  - tar -xzf armadillo.tar.gz -C ./armadillo --strip-components=1
  - cd armadillo
  - cmake .
  - make -j 4
  - sudo make install
  - cd ..
  - rm -Rf armadillo armadillo.tar.gz

  # Catch
  - wget -O catch.tar.gz https://github.com/philsquared/Catch/archive/3e0c5018123e7e32b3c35f4169cbdca4bcb8f332.tar.gz
  - mkdir catch
  - tar -xzf catch.tar.gz -C ./catch --strip-components=1
  - sudo cp -R catch/single_include/catch.hpp /usr/local/include/
  - rm -Rf catch catch.tar.gz
  
  # MPI (This will actually install 3.x on Ubuntu 14.04+ and 2.x on previous versions)
  - sudo apt-get install -qq libmpich2-dev

script:
  - if [ "$CXX" == "g++" ]; then cmake -DRUN_TESTS=ON -DUSE_MPI=ON .; fi
  - if [ "$CXX" == "clang++" ]; then cmake -DRUN_TESTS=ON -DUSE_MPI=ON .; fi
  - make -j 4
  - sudo make install
