language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  # Install OpenBLAS
  - sudo apt-get install -qq libopenblas-dev
  
  # Install Armadillo C++
  - wget -O armadillo.tar.gz http://downloads.sourceforge.net/project/arma/armadillo-4.400.1.tar.gz
  - mkdir armadillo
  - tar -xzf armadillo.tar.gz -C ./armadillo --strip-components=1
  - cd armadillo
  - cmake .
  - make
  - sudo make install
  - cd ..

script: 
  - cmake .
  - make
  - bin/test
