language: cpp

compiler:
  - clang
  - gcc

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  
  # Install OpenBLAS
  - sudo apt-get install -qq libopenblas-dev
  
  # Install Armadillo C++
  - wget -O armadillo.tar.gz http://downloads.sourceforge.net/project/arma/armadillo-4.400.1.tar.gz
  - mkdir armadillo
  - tar -xzf armadillo.tar.gz -C ./armadillo --strip-components=1
  - cd armadillo
  - cmake .
  - make
  - sudo make install
  - cd ..

script: 
  - cmake .
  - make
  - bin/test
